name: Automated Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  run-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Print context
        run: |
          echo "üéâ The job was automatically triggered by a ${GITHUB_EVENT_NAME} event."
          echo "üêß This job is now running on a ${RUNNER_OS} server hosted by GitHub!"
          echo "üîé The name of your branch is ${GITHUB_REF} and your repository is ${GITHUB_REPOSITORY}."
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          RUNNER_OS: ${{ runner.os }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Confirm checkout
        run: |
          echo "üí° The ${GITHUB_REPOSITORY} repository has been cloned to the runner."
          echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: node --run prettier
      - name: Check linting
        run: node --run lint
      - name: Print job status
        run: echo "üçè This job's status is ${JOB_STATUS}."
        env:
          JOB_STATUS: ${{ job.status }}
